#include"map.h"
#include "raylib.h"
#include "furniture.h"

#define EMPTY {CELL_EMPTY, {{0,0,0,0}, 8, 9, 0, 0}}
#define MEDICINE_EMPTY {CELL_EMPTY, {{0,0,0,0}, 10, 11, 0, 0}}
#define LIBRARY_EMPTY {CELL_EMPTY, {{0,0,0,0}, 12, 13, 0, 0}}
#define STORAGE_EMPTY {CELL_EMPTY, {{0,0,0,0}, 14, 15, 0, 0}}
#define ROOM1_EMPTY {CELL_EMPTY, {{0,0,0,0}, 16, 9, 0, 0}}
#define ROOM2_EMPTY {CELL_EMPTY, {{0,0,0,0}, 17, 9, 0, 0}}
#define ROOM3_EMPTY {CELL_EMPTY, {{0,0,0,0}, 18, 9, 0, 0}}
#define WALL {CELL_WALL,  {{0,0,0,0}, 0, 0, 0, 0}}
#define ROOM1_WALL_N {CELL_WALL,  {{0,1,0,0}, 0, 0, 0, 0}}
#define ROOM1_WALL_S {CELL_WALL,  {{1,0,0,0}, 0, 0, 0, 0}}
#define ROOM1_WALL_W {CELL_WALL,  {{0,0,0,1}, 0, 0, 0, 0}}
#define ROOM1_WALL_E {CELL_WALL,  {{0,0,1,0}, 0, 0, 0, 0}}
#define ROOM2_WALL_N {CELL_WALL,  {{0,2,0,0}, 0, 0, 0, 0}}
#define ROOM2_WALL_S {CELL_WALL,  {{2,0,0,0}, 0, 0, 0, 0}}
#define ROOM2_WALL_W {CELL_WALL,  {{0,0,0,2}, 0, 0, 0, 0}}
#define ROOM2_WALL_E {CELL_WALL,  {{0,0,2,4}, 0, 0, 0, 0}}
#define ROOM3_WALL_N {CELL_WALL,  {{0,3,0,0}, 0, 0, 0, 0}}
#define ROOM3_WALL_S {CELL_WALL,  {{3,4,0,0}, 0, 0, 0, 0}}
#define ROOM3_WALL_W {CELL_WALL,  {{0,0,0,3}, 0, 0, 0, 0}}
#define ROOM3_WALL_E {CELL_WALL,  {{0,0,3,0}, 0, 0, 0, 0}}
#define STORAGE_WALL_N {CELL_WALL,  {{0,4,0,0}, 0, 0, 0, 0}}
#define STORAGE_WALL_S {CELL_WALL,  {{4,0,0,0}, 0, 0, 0, 0}}
#define STORAGE_WALL_W {CELL_WALL,  {{0,0,0,4}, 0, 0, 0, 0}}
#define STORAGE_WALL_E {CELL_WALL,  {{0,0,4,0}, 0, 0, 0, 0}}
#define MEDICINE_WALL_N {CELL_WALL,  {{0,5,0,0}, 0, 0, 0, 0}}
#define MEDICINE_WALL_S {CELL_WALL,  {{5,0,0,0}, 0, 0, 0, 0}}
#define MEDICINE_WALL_W {CELL_WALL,  {{0,0,0,5}, 0, 0, 0, 0}}
#define MEDICINE_WALL_E {CELL_WALL,  {{0,0,5,0}, 0, 0, 0, 0}}
#define LIBRARY_WALL_N {CELL_WALL,  {{0,6,0,0}, 0, 0, 0, 0}}
#define LIBRARY_WALL_S {CELL_WALL,  {{6,0,0,0}, 0, 0, 0, 0}}
#define LIBRARY_WALL_W {CELL_WALL,  {{0,0,0,6}, 0, 0, 0, 0}}
#define LIBRARY_WALL_E {CELL_WALL,  {{0,0,6,0}, 0, 0, 0, 0}}
#define DOOR {CELL_DOOR,  {{0,0,0,0}, 8, 8, 7, 0}}
#define LOCKED_DOOR {CELL_LOCKED_DOOR, {{0,0,0,0}, 0, 0, 7, 0}}

Cell map[MAP_HEIGHT][MAP_WIDTH] = {
    { WALL, ROOM1_WALL_N, ROOM1_WALL_N, ROOM1_WALL_N, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, ROOM2_WALL_N, ROOM2_WALL_N, ROOM2_WALL_N, WALL, STORAGE_WALL_N, STORAGE_WALL_N, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
    { ROOM1_WALL_W, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, ROOM2_WALL_W, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_WALL_E, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL },
    { ROOM1_WALL_W, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, ROOM2_WALL_W, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_WALL_E, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL },
    { ROOM1_WALL_W, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, ROOM2_WALL_W, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_WALL_E, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL },
    { ROOM1_WALL_W, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_EMPTY, ROOM1_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, ROOM2_WALL_W, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_EMPTY, ROOM2_WALL_E, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, WALL },
    { WALL, ROOM1_WALL_S, ROOM1_WALL_S, DOOR, WALL, WALL, WALL, DOOR, WALL, WALL, WALL, DOOR, WALL, ROOM2_WALL_S, ROOM2_WALL_S, DOOR, WALL, STORAGE_WALL_S, DOOR, WALL, DOOR, WALL, WALL, WALL, DOOR, WALL, WALL, WALL, DOOR, WALL, WALL, WALL, DOOR, WALL, WALL, WALL },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL },
    { WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL, DOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, DOOR, WALL, EMPTY, EMPTY, WALL, ROOM3_WALL_N, ROOM3_WALL_N, ROOM3_WALL_N, ROOM3_WALL_N, WALL },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, DOOR, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_WALL_E },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, ROOM3_WALL_W, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_WALL_E },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, ROOM3_WALL_W, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_EMPTY, ROOM3_WALL_E },
    { WALL, MEDICINE_WALL_N, MEDICINE_WALL_N, MEDICINE_WALL_N, MEDICINE_WALL_N, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, ROOM3_WALL_S, ROOM3_WALL_S, ROOM3_WALL_S, ROOM3_WALL_S, WALL },
    { MEDICINE_WALL_W, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_WALL_E, EMPTY, EMPTY, WALL, DOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, DOOR, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { MEDICINE_WALL_W, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, DOOR, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, DOOR, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { MEDICINE_WALL_W, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_WALL_E, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { MEDICINE_WALL_W, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_EMPTY, MEDICINE_WALL_E, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { WALL, MEDICINE_WALL_S, MEDICINE_WALL_S, MEDICINE_WALL_S, DOOR, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, STORAGE_WALL_W, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_EMPTY, STORAGE_WALL_E },
    { WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, STORAGE_WALL_S, STORAGE_WALL_S, STORAGE_WALL_S, STORAGE_WALL_S, WALL },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL, LIBRARY_WALL_N, LIBRARY_WALL_N, LIBRARY_WALL_N, LIBRARY_WALL_N, LIBRARY_WALL_N, LIBRARY_WALL_N, LIBRARY_WALL_N, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, DOOR, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, DOOR, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, LIBRARY_WALL_W, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_EMPTY, LIBRARY_WALL_E, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL, LIBRARY_WALL_S, LIBRARY_WALL_S, LIBRARY_WALL_S, LIBRARY_WALL_S, LIBRARY_WALL_S, LIBRARY_WALL_S, LIBRARY_WALL_S, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DOOR, EMPTY, EMPTY, WALL, EMPTY, EMPTY, WALL },
    { WALL, LOCKED_DOOR, LOCKED_DOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, LOCKED_DOOR, LOCKED_DOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, LOCKED_DOOR, LOCKED_DOOR, WALL }
};

DoorState doors[MAP_HEIGHT][MAP_WIDTH] = { 0 };

bool IsSolid(Cell cell, DoorState* door) {
    if (cell.type == CELL_WALL) return true;
    if (cell.type == CELL_LOCKED_DOOR) return true;
    if (cell.type == CELL_DOOR) {
        return !(door->is_open && door->offset >= 1.0);
    }
    return false;
}

void UpdateDoors(DoorState doors[MAP_HEIGHT][MAP_WIDTH]) {
    float dt = GetFrameTime();

    for (int y = 0; y < MAP_HEIGHT; y++) {
        for (int x = 0; x < MAP_WIDTH; x++) {
            DoorState* door = &doors[y][x];
            if (!door->is_opening) continue;

            door->offset += door->dir * 2.0f * dt;

            if (door->offset >= 1.0f) {
                door->offset = 1.0f;
                door->is_opening = false;
                door->is_open = true;
            }
            else if (door->offset <= 0.0f) {
                door->offset = 0.0f;
                door->is_opening = false;
                door->is_open = false;
            }
        }
    }
}